In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 10),
        nn.ReLU(),
        nn.Linear(10, 10),
        nn.ReLU(),
        nn.Linear(10, 1),
        nn.Sigmoid())

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.4796],
        [0.4855],
        [0.4858],
        [0.4833],
        [0.4846],
        [0.4840],
        [0.4828],
        [0.4803],
        [0.4815],
        [0.4846]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.network[4].weight

Parameter containing:
tensor([[-0.1729, -0.1853, -0.1109,  0.0096, -0.1085,  0.0600,  0.0351, -0.1533,
          0.0846,  0.0628]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.0217], requires_grad=True)

In [ ]:
pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 10]                  60
│    └─ReLU: 2-2                         [10, 10]                  --
│    └─Linear: 2-3                       [10, 10]                  110
│    └─ReLU: 2-4                         [10, 10]                  --
│    └─Linear: 2-5                       [10, 1]                   11
│    └─Sigmoid: 2-6                      [10, 1]                   --
Total params: 181
Trainable params: 181
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00